# Generated by Django 5.1.1 on 2024-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField(default=0, unique=True)),
            ],
            options={
                'db_table': 'admins',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'managed': True},
        ),
    ]
