# Generated by Django 5.1.5 on 2025-01-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_admins_alter_suggestion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='classtime',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='groupschedule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='teacherdepartment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='weekday',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='weektype',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='suggestion',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='database.user'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='closed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='closed_text',
            field=models.TextField(default='', null=True),
        ),
    ]
